export const ALLCONTACT_DETAILS_LOADING = "ALLCONTACT_DETAILS:LOADING";

export const ALLCONTACT_DETAILS_SUCCESS = "ALLCONTACT_DETAILS:SUCCESS";

export const ALLCONTACT_DETAILS_ERROR = "ALLCONTACT_DETAILS:ERROR";

export const CONTACT_DETAILS_ID_LOADING = "CONTACT_DETAILS_ID:LOADING";

export const CONTACT_DETAILS_ID_SUCCESS = "CONTACT_DETAILS_ID:SUCCESS";

export const CONTACT_DETAILS_ID_ERROR = "CONTACT_DETAILS_ID:ERROR";

export const DELETE_CONTACT_DETAILS_ID_LOADING =
  "DELETE_CONTACT_DETAILS_ID:LOADING";

export const DELETE_CONTACT_DETAILS_ID_SUCCESS =
  "DELETE_CONTACT_DETAILS_ID:SUCCESS";

export const DELETE_CONTACT_DETAILS_ID_ERROR = "DELETE_CONTACTDETAILS_ID:ERROR";

export const UPDATE_CONTACT_DETAILS_ID_LOADING =
  "UPDATE_CONTACT_DETAILS_ID:LOADING";

export const UPDATE_CONTACT_DETAILS_ID_SUCCESS =
  "UPDATE_CONTACT_DETAILS_ID:SUCCESS";

export const UPDATE_CONTACT_DETAILS_ID_ERROR = "UPDATE_CONTACTDETAILS_ID:ERROR";

export const INSERT_CONTACT_DETAILS_LOADING = "INSERT_CONTACT_DETAILS:LOADING";

export const INSERT_CONTACT_DETAILS_SUCCESS = "INSERT_CONTACT_DETAILS:SUCCESS";

export const INSERT_CONTACT_DETAILS_ERROR = "INSERT_CONTACTDETAILS:ERROR";
